'use client';

/**
 * CareerAdviceCard.tsx
 *
 * UPGRADE 3 dashboard component — AI Career Insights.
 *
 * Displays the personalised career advice generated by CareerAdvisorEngine.
 * Designed to slot into:
 *   - /career-health page (alongside existing CHI cards)
 *   - /dashboard page (as a featured insight card)
 *
 * Usage:
 *   import { CareerAdviceCard } from '@/components/semantic/CareerAdviceCard';
 *   <CareerAdviceCard />
 */

import { useCareerAdvice } from '@/hooks/useSemanticSkills';
import { cn } from '@/utils/cn';

// ─── Skill priority pill ──────────────────────────────────────────────────────

function PrioritySkill({ skill, rank }: { skill: string; rank: number }) {
  const colors = [
    'bg-violet-100 text-violet-700 border-violet-200',
    'bg-indigo-100 text-indigo-700 border-indigo-200',
    'bg-blue-100   text-blue-700   border-blue-200',
  ];
  return (
    <div className={cn(
      'flex items-center gap-1.5 rounded-full px-2.5 py-1 border text-xs font-medium',
      colors[rank] || colors[2]
    )}>
      <span className="text-[10px] font-bold opacity-60">#{rank + 1}</span>
      {skill}
    </div>
  );
}

// ─── Metric tile ──────────────────────────────────────────────────────────────

function MetricTile({
  icon, label, value, accent,
}: {
  icon: React.ReactNode; label: string; value: string; accent: string;
}) {
  return (
    <div className={cn('rounded-xl p-3 flex items-start gap-2', accent)}>
      <div className="mt-0.5 shrink-0">{icon}</div>
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-wide opacity-70">{label}</p>
        <p className="text-sm font-bold mt-0.5">{value}</p>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface CareerAdviceCardProps {
  className?: string;
}

export function CareerAdviceCard({ className }: CareerAdviceCardProps) {
  const { data, isLoading, isError, refetch } = useCareerAdvice();

  // ── Loading ─────────────────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <div className={cn('rounded-2xl border border-surface-100 bg-white shadow-sm overflow-hidden', className)}>
        <div className="h-1.5 bg-gradient-to-r from-violet-400 via-indigo-400 to-blue-400 animate-pulse" />
        <div className="p-5 space-y-3">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-xl bg-surface-100 animate-pulse" />
            <div className="space-y-1">
              <div className="h-3.5 w-32 rounded bg-surface-100 animate-pulse" />
              <div className="h-2.5 w-20 rounded bg-surface-100 animate-pulse" />
            </div>
          </div>
          <div className="space-y-2">
            <div className="h-3 w-full rounded bg-surface-100 animate-pulse" />
            <div className="h-3 w-4/5 rounded bg-surface-100 animate-pulse" />
            <div className="h-3 w-3/5 rounded bg-surface-100 animate-pulse" />
          </div>
          <div className="grid grid-cols-2 gap-2">
            <div className="h-14 rounded-xl bg-surface-100 animate-pulse" />
            <div className="h-14 rounded-xl bg-surface-100 animate-pulse" />
          </div>
        </div>
      </div>
    );
  }

  // ── Error ───────────────────────────────────────────────────────────────────
  if (isError) {
    return (
      <div className={cn('rounded-2xl border border-rose-100 bg-rose-50 p-5', className)}>
        <p className="text-sm font-semibold text-rose-700 mb-1">Career Insights Unavailable</p>
        <p className="text-xs text-rose-500 mb-3">Could not load your career advice right now.</p>
        <button
          onClick={() => refetch()}
          className="text-xs font-semibold text-rose-700 hover:underline"
        >
          Try again →
        </button>
      </div>
    );
  }

  if (!data) return null;

  // ── Loaded ──────────────────────────────────────────────────────────────────
  return (
    <div className={cn('rounded-2xl border border-surface-100 bg-white shadow-sm overflow-hidden', className)}>
      {/* Gradient accent */}
      <div className="h-1.5 bg-gradient-to-r from-violet-500 via-indigo-500 to-blue-500" />

      <div className="p-5">
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-100">
              <svg className="h-5 w-5 text-violet-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-surface-900">AI Career Insight</h3>
              <p className="text-[10px] text-surface-400 uppercase tracking-wide">
                Personalised · Updated {_relativeTime(data.generated_at)}
              </p>
            </div>
          </div>
          {data._fallback && (
            <span className="text-[10px] text-amber-600 bg-amber-50 border border-amber-200 rounded-full px-2 py-0.5 font-medium">
              General
            </span>
          )}
        </div>

        {/* Main insight */}
        <blockquote className="relative pl-4 mb-4">
          <div className="absolute left-0 top-0 bottom-0 w-1 rounded-full bg-gradient-to-b from-violet-400 to-indigo-400" />
          <p className="text-sm text-surface-800 leading-relaxed">{data.career_insight}</p>
        </blockquote>

        {/* Key opportunity */}
        <div className="rounded-xl bg-indigo-50 border border-indigo-100 p-3 mb-4">
          <div className="flex items-start gap-2">
            <svg className="h-4 w-4 text-indigo-600 mt-0.5 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="9 11 12 14 22 4" /><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
            </svg>
            <div>
              <p className="text-[10px] font-bold text-indigo-700 uppercase tracking-wide mb-0.5">Key Next Step</p>
              <p className="text-xs text-indigo-800">{data.key_opportunity}</p>
            </div>
          </div>
        </div>

        {/* Metrics grid */}
        <div className="grid grid-cols-2 gap-2 mb-4">
          <MetricTile
            icon={
              <svg className="h-4 w-4 text-emerald-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="12" y1="1" x2="12" y2="23" /><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
              </svg>
            }
            label="Salary Potential"
            value={data.salary_potential}
            accent="bg-emerald-50 text-emerald-900 border border-emerald-100"
          />
          <MetricTile
            icon={
              <svg className="h-4 w-4 text-blue-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" />
              </svg>
            }
            label="Timeline"
            value={data.timeline}
            accent="bg-blue-50 text-blue-900 border border-blue-100"
          />
        </div>

        {/* Priority skills */}
        {data.skills_to_prioritise?.length > 0 && (
          <div>
            <p className="text-[10px] font-semibold text-surface-500 uppercase tracking-wide mb-2">
              Skills to Prioritise
            </p>
            <div className="flex flex-wrap gap-1.5">
              {data.skills_to_prioritise.map((s, i) => (
                <PrioritySkill key={s} skill={s} rank={i} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function _relativeTime(iso?: string): string {
  if (!iso) return 'recently';
  const diff = Date.now() - new Date(iso).getTime();
  if (diff < 60_000) return 'just now';
  if (diff < 3_600_000) return `${Math.round(diff / 60_000)}m ago`;
  return `${Math.round(diff / 3_600_000)}h ago`;
}