/**
 * src/modules/skill-evolution/services/skills.api.ts
 *
 * API client for the Skill Evolution Engine endpoints.
 * Mirrors the pattern in education.api.ts — uses apiFetch from apiClient.ts.
 */

import { apiFetch } from '@/services/apiClient';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SkillRecommendation {
  skill:            string;
  impact:           number;       // 0–100
  demand_score:     number;       // 0–100 (from LMI)
  career_relevance: number;       // 0–1
  growth_rate:      number;       // e.g. 0.22 → 22%/yr growth
  learning_order:   number;       // 1 = learn first
  rationale:        string;
}

export interface RoadmapStep {
  step:      number;
  skill:     string;
  impact:    number;
  rationale: string;
}

export interface SkillRecommendationsResponse {
  skills:             SkillRecommendation[];
  roadmap:            RoadmapStep[];
  top_career:         string | null;
  recommended_stream: string | null;
  engine_version:     string | null;
  calculated_at:      string | null;
}

export interface StudentSkill {
  student_id:        string;
  skill_name:        string;
  proficiency_level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  impact_score:      number;
  career_relevance:  number;
  demand_score:      number;
}

// ─── API functions ────────────────────────────────────────────────────────────

/**
 * Fetch ranked skill recommendations + learning roadmap for a student.
 * The data is generated by the orchestrator pipeline — run analysis first.
 */
export function getSkillRecommendations(
  studentId: string
): Promise<SkillRecommendationsResponse> {
  return apiFetch(`/education/skills/recommendations/${studentId}`);
}

/**
 * Fetch raw per-skill proficiency rows for a student.
 */
export function getStudentSkills(
  studentId: string
): Promise<{ skills: StudentSkill[] }> {
  return apiFetch(`/education/skills/student-skills/${studentId}`);
}

export const skillsApi = {
  getSkillRecommendations,
  getStudentSkills,
};
